/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primeiroprogrma;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maikiely
 */
public class NomeSobrenomeForm extends javax.swing.JFrame {
       
    ArrayList a = new ArrayList();//esse vetor esta sendo usado para guarda os nomes que estao sendo digitados.
    BufferedWriter br; // Esse arquivo esta guardando as informações do vetor.
    /**
     * Creates new form NomeSobrenomeForm
     */
    public NomeSobrenomeForm() {
        
        try {
            // crinado o arquivo 
            initComponents();
            FileWriter fw = null;
            File f = new File("arquivo.txt");
            fw = new FileWriter(f,true);
            br = new BufferedWriter(fw); 
        } catch (IOException ex) { 
            // mensage de erro caso de algum problema
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1Nome = new javax.swing.JLabel();
        jLabel2Sobrenome = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        Leitura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Nome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1Nome.setText("Digite seu primeiro nome:");

        jLabel2Sobrenome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2Sobrenome.setText("Digite seu  sobrenome:");

        jTextFieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobrenomeActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jButtonOK.setBackground(new java.awt.Color(153, 153, 255));
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Idade:");

        jTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeActionPerformed(evt);
            }
        });

        Leitura.setText("Leitura");
        Leitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeituraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Leitura)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonOK))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Nome)
                            .addComponent(jLabel2Sobrenome)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2Sobrenome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(Leitura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>                        

    private void jTextFieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Pessoa p = new Pessoa();
        if(jTextFieldSobrenome.getText().isEmpty() || jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"O nome e o sobrenome devem ser preenchidos" , "ERRO DE UTILIZACAO", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                String msg = "Bem Vindo " + jTextFieldNome.getText()+" " +jTextFieldSobrenome.getText();
                JOptionPane.showMessageDialog(rootPane,msg , "BEM VINDO", JOptionPane.INFORMATION_MESSAGE);
            
                p.setNome(jTextFieldNome.getText()); // pega o atributo da classe pessoa e salva no vetor
                p.setSobrenome(jTextFieldSobrenome.getText());
                int idade = Integer.parseInt(jTextFieldIdade.getText()); // faz a conversão de String para inteiro
                p.setIdade(idade);
            
                a.add(p);
           
                br.write(p.toStringToFile()); // escrevendo no arquivo
                br.newLine(); // saltando uma linha
                br.flush();// para salvar os dados no arquibvo e não só no buffer.
                
            } catch (IOException ex) {
                 JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
        System.out.println(a);
        //jLabel1Nome.setForeground(Color.blue);
        //jTextFieldNome.setBackground(Color.red);
    }                                         

    private void jTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void LeituraActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //Criando método para leitura de arquivo.
        try{
            String textFile = new String();
            File f = new File("arquivo.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            String line = br.readLine();
            while(line != null){
                Pessoa p = new Pessoa();
                StringTokenizer st = new StringTokenizer(line,"#"); //separado  
                String nome = st.nextToken();
                String sobrenome = st.nextToken();
                String idade = st.nextToken();
                p.setNome(nome);
                p.setSobrenome(sobrenome);
                int idadeInt = Integer.parseInt(idade);
                p.setIdade(idadeInt);
                
                JOptionPane.showInputDialog(this,p.toString());
               
                textFile = textFile + "\n" + line;
                line = br.readLine();
            }
            JOptionPane.showInputDialog(this,textFile);
        }catch(IOException ex){
            ex.printStackTrace();
        }
        
        
        
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NomeSobrenomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NomeSobrenomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NomeSobrenomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NomeSobrenomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NomeSobrenomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Leitura;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JLabel jLabel2Sobrenome;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration                   
}
